[project]
name = "string-art-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aggdraw>=1.3.19",
    "numba>=0.61.2",
    "numpy>=2.2.6",
    "pillow>=11.3.0",
]
